/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.CDashboard;
import model.MDashboard;


public class VDashboard extends javax.swing.JPanel {


    public VDashboard() {
        initComponents();
        setStats();
        LoadIncomeTable();
        LoadExpenseTable();
    }
    
    CDashboard cd = new CDashboard();

    public void setStats()
    {
        lbl_remaningbudget.setText("$ "+cd.getTotalBalance());
        lbl_totalexpenses.setText("$ "+cd.getTotalExpense());
        lbl_totalincome.setText("$ "+cd.getTotalIncome());
    }
    
    public void LoadIncomeTable()
    {
        cd.LoadIncomeTable(this);
    }
    
    public void LoadExpenseTable()
    {
        cd.LoadExpenseTable(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_remaningbudget = new javax.swing.JPanel();
        lbl_label = new javax.swing.JLabel();
        lbl_totalexpenses = new javax.swing.JLabel();
        pnl_remaningbudget1 = new javax.swing.JPanel();
        lbl_label1 = new javax.swing.JLabel();
        lbl_remaningbudget = new javax.swing.JLabel();
        pnl_remaningbudget3 = new javax.swing.JPanel();
        lbl_label3 = new javax.swing.JLabel();
        lbl_totalincome = new javax.swing.JLabel();
        pnl_retreive_data = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_incomedetials = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_expensedetials = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(788, 600));
        setMinimumSize(new java.awt.Dimension(788, 600));
        setLayout(null);

        pnl_remaningbudget.setBackground(new java.awt.Color(204, 0, 0));

        lbl_label.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        lbl_label.setForeground(new java.awt.Color(255, 255, 255));
        lbl_label.setText("Total Expenses");

        lbl_totalexpenses.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 30)); // NOI18N
        lbl_totalexpenses.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalexpenses.setText("$ 100000");

        javax.swing.GroupLayout pnl_remaningbudgetLayout = new javax.swing.GroupLayout(pnl_remaningbudget);
        pnl_remaningbudget.setLayout(pnl_remaningbudgetLayout);
        pnl_remaningbudgetLayout.setHorizontalGroup(
            pnl_remaningbudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_remaningbudgetLayout.createSequentialGroup()
                .addGroup(pnl_remaningbudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_remaningbudgetLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbl_totalexpenses))
                    .addGroup(pnl_remaningbudgetLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl_label)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnl_remaningbudgetLayout.setVerticalGroup(
            pnl_remaningbudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_remaningbudgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_label)
                .addGap(18, 18, 18)
                .addComponent(lbl_totalexpenses)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(pnl_remaningbudget);
        pnl_remaningbudget.setBounds(298, 46, 205, 113);

        pnl_remaningbudget1.setBackground(new java.awt.Color(255, 153, 0));

        lbl_label1.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        lbl_label1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_label1.setText("Remaning Budget");

        lbl_remaningbudget.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 30)); // NOI18N
        lbl_remaningbudget.setForeground(new java.awt.Color(255, 255, 255));
        lbl_remaningbudget.setText("$ 100000");

        javax.swing.GroupLayout pnl_remaningbudget1Layout = new javax.swing.GroupLayout(pnl_remaningbudget1);
        pnl_remaningbudget1.setLayout(pnl_remaningbudget1Layout);
        pnl_remaningbudget1Layout.setHorizontalGroup(
            pnl_remaningbudget1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_remaningbudget1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(pnl_remaningbudget1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_remaningbudget)
                    .addComponent(lbl_label1))
                .addGap(38, 38, 38))
        );
        pnl_remaningbudget1Layout.setVerticalGroup(
            pnl_remaningbudget1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_remaningbudget1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_remaningbudget)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(pnl_remaningbudget1);
        pnl_remaningbudget1.setBounds(70, 46, 198, 113);

        pnl_remaningbudget3.setBackground(new java.awt.Color(0, 102, 0));

        lbl_label3.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        lbl_label3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_label3.setText("Total Income");

        lbl_totalincome.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 30)); // NOI18N
        lbl_totalincome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalincome.setText("$ 100000");

        javax.swing.GroupLayout pnl_remaningbudget3Layout = new javax.swing.GroupLayout(pnl_remaningbudget3);
        pnl_remaningbudget3.setLayout(pnl_remaningbudget3Layout);
        pnl_remaningbudget3Layout.setHorizontalGroup(
            pnl_remaningbudget3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_remaningbudget3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(pnl_remaningbudget3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_remaningbudget3Layout.createSequentialGroup()
                        .addComponent(lbl_label3)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_remaningbudget3Layout.createSequentialGroup()
                        .addComponent(lbl_totalincome)
                        .addGap(36, 36, 36))))
        );
        pnl_remaningbudget3Layout.setVerticalGroup(
            pnl_remaningbudget3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_remaningbudget3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_label3)
                .addGap(18, 18, 18)
                .addComponent(lbl_totalincome)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(pnl_remaningbudget3);
        pnl_remaningbudget3.setBounds(527, 46, 210, 113);

        pnl_retreive_data.setPreferredSize(new java.awt.Dimension(400, 400));

        table_incomedetials.setBackground(new java.awt.Color(204, 204, 204));
        table_incomedetials.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 12)); // NOI18N
        table_incomedetials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Income Date", "Income Name", "Income Category", "Income Amount", "Income Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_incomedetials.setRowHeight(50);
        jScrollPane1.setViewportView(table_incomedetials);

        jLabel2.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Recent Income Records");

        table_expensedetials.setBackground(new java.awt.Color(204, 204, 204));
        table_expensedetials.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 12)); // NOI18N
        table_expensedetials.setForeground(new java.awt.Color(0, 0, 0));
        table_expensedetials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Expense Date", "Expense Name", "Expense Category", "Expense Amount", "Expense Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_expensedetials.setRowHeight(50);
        jScrollPane2.setViewportView(table_expensedetials);

        jLabel3.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Recent Expense Records");

        javax.swing.GroupLayout pnl_retreive_dataLayout = new javax.swing.GroupLayout(pnl_retreive_data);
        pnl_retreive_data.setLayout(pnl_retreive_dataLayout);
        pnl_retreive_dataLayout.setHorizontalGroup(
            pnl_retreive_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_retreive_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_retreive_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(pnl_retreive_dataLayout.createSequentialGroup()
                        .addGroup(pnl_retreive_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_retreive_dataLayout.setVerticalGroup(
            pnl_retreive_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_retreive_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        add(pnl_retreive_data);
        pnl_retreive_data.setBounds(70, 210, 670, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_label;
    private javax.swing.JLabel lbl_label1;
    private javax.swing.JLabel lbl_label3;
    private javax.swing.JLabel lbl_remaningbudget;
    private javax.swing.JLabel lbl_totalexpenses;
    private javax.swing.JLabel lbl_totalincome;
    private javax.swing.JPanel pnl_remaningbudget;
    private javax.swing.JPanel pnl_remaningbudget1;
    private javax.swing.JPanel pnl_remaningbudget3;
    public javax.swing.JPanel pnl_retreive_data;
    public javax.swing.JTable table_expensedetials;
    public javax.swing.JTable table_incomedetials;
    // End of variables declaration//GEN-END:variables
}
