
package view;

import Reports.VReportFrom;
import java.awt.Color;
import javax.swing.*;
import view.*;
import control.CHome;

public class VHome extends javax.swing.JFrame {

    private static String acc_email = VSignIn.getEmail();
    
    public VHome() {
        initComponents();
        SetButtonColor(btn_load_dashboard);
        ShowAccDetials();
        VDashboard pnl = new VDashboard();
        SwitchUI(pnl);
        SetButtonColor(btn_load_dashboard);
    }
    
    void ShowAccDetials()
    {
        CHome ch = new CHome();
        lbl_accemail.setText(acc_email);
        lbl_username.setText(ch.getFirstName(acc_email) + " " + ch.getLastName(acc_email));
    }
    
    void SwitchUI(JPanel panel)
    {
        pane_load_ui.removeAll();
        pane_load_ui.add(panel);
        pane_load_ui.repaint();
        pane_load_ui.revalidate();
    }
    
    void SetButtonColor(JButton btn)
    {
        ResetButtonColor();
        btn.setBackground( new Color(0,0,102));
        btn.setForeground(Color.WHITE);
    }
    
    void ResetButtonColor()
    {
        btn_load_dashboard.setBackground( Color.WHITE);
        btn_load_dashboard.setForeground(Color.BLACK);
        
        btn_load_income.setBackground( Color.WHITE);
        btn_load_income.setForeground(Color.BLACK);
        
        btn_load_expenses.setBackground( Color.WHITE);
        btn_load_expenses.setForeground(Color.BLACK);
        
        btn_load_goals.setBackground( Color.WHITE);
        btn_load_goals.setForeground(Color.BLACK);
        
        btn_load_reports.setBackground( Color.WHITE);
        btn_load_reports.setForeground(Color.BLACK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_design1 = new javax.swing.JPanel();
        pnl_menu = new keeptoo.KGradientPanel();
        pnl_profile_info = new javax.swing.JPanel();
        lbl_pfp = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_accemail = new javax.swing.JLabel();
        btn_load_income = new javax.swing.JButton();
        btn_load_expenses = new javax.swing.JButton();
        btn_load_dashboard = new javax.swing.JButton();
        btn_load_goals = new javax.swing.JButton();
        btn_load_reports = new javax.swing.JButton();
        btn_load_signin = new javax.swing.JButton();
        pnl_control_bar = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        pane_load_ui = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 650));

        pnl_design1.setBackground(new java.awt.Color(0, 0, 102));
        pnl_design1.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout pnl_design1Layout = new javax.swing.GroupLayout(pnl_design1);
        pnl_design1.setLayout(pnl_design1Layout);
        pnl_design1Layout.setHorizontalGroup(
            pnl_design1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl_design1Layout.setVerticalGroup(
            pnl_design1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnl_menu.setkEndColor(new java.awt.Color(243, 243, 243));
        pnl_menu.setkStartColor(new java.awt.Color(255, 255, 255));

        pnl_profile_info.setBackground(new java.awt.Color(255, 255, 255));

        lbl_pfp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_username.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(0, 0, 0));
        lbl_username.setText("User Name");

        lbl_accemail.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 10)); // NOI18N
        lbl_accemail.setForeground(new java.awt.Color(0, 0, 0));
        lbl_accemail.setText("user@email.com");

        javax.swing.GroupLayout pnl_profile_infoLayout = new javax.swing.GroupLayout(pnl_profile_info);
        pnl_profile_info.setLayout(pnl_profile_infoLayout);
        pnl_profile_infoLayout.setHorizontalGroup(
            pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_accemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        pnl_profile_infoLayout.setVerticalGroup(
            pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                .addGroup(pnl_profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_profile_infoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbl_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_accemail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_profile_infoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_load_income.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_income.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        btn_load_income.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_income.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-stack-of-money-24.png"))); // NOI18N
        btn_load_income.setText("Incomes");
        btn_load_income.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_income.setBorderPainted(false);
        btn_load_income.setFocusPainted(false);
        btn_load_income.setFocusable(false);
        btn_load_income.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_income.setIconTextGap(25);
        btn_load_income.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_income.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_incomeActionPerformed(evt);
            }
        });

        btn_load_expenses.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_expenses.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        btn_load_expenses.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_expenses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-payment-24.png"))); // NOI18N
        btn_load_expenses.setText("Expenses");
        btn_load_expenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_expenses.setBorderPainted(false);
        btn_load_expenses.setFocusPainted(false);
        btn_load_expenses.setFocusable(false);
        btn_load_expenses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_expenses.setIconTextGap(25);
        btn_load_expenses.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_expenses.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_expensesActionPerformed(evt);
            }
        });

        btn_load_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_dashboard.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        btn_load_dashboard.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-dashboard-24.png"))); // NOI18N
        btn_load_dashboard.setText("Dashboard");
        btn_load_dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_dashboard.setBorderPainted(false);
        btn_load_dashboard.setFocusPainted(false);
        btn_load_dashboard.setFocusable(false);
        btn_load_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_dashboard.setIconTextGap(25);
        btn_load_dashboard.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_dashboard.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_dashboardActionPerformed(evt);
            }
        });

        btn_load_goals.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_goals.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        btn_load_goals.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_goals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-goal-24.png"))); // NOI18N
        btn_load_goals.setText("Goals");
        btn_load_goals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_goals.setBorderPainted(false);
        btn_load_goals.setFocusPainted(false);
        btn_load_goals.setFocusable(false);
        btn_load_goals.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_goals.setIconTextGap(25);
        btn_load_goals.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_goals.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_goalsActionPerformed(evt);
            }
        });

        btn_load_reports.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_reports.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        btn_load_reports.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-pie-chart-24.png"))); // NOI18N
        btn_load_reports.setText("Reports");
        btn_load_reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_reports.setBorderPainted(false);
        btn_load_reports.setFocusPainted(false);
        btn_load_reports.setFocusable(false);
        btn_load_reports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_reports.setIconTextGap(25);
        btn_load_reports.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_reports.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_reportsActionPerformed(evt);
            }
        });

        btn_load_signin.setBackground(new java.awt.Color(255, 255, 255));
        btn_load_signin.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 18)); // NOI18N
        btn_load_signin.setForeground(new java.awt.Color(0, 0, 0));
        btn_load_signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-exit-24.png"))); // NOI18N
        btn_load_signin.setText("Log Out");
        btn_load_signin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        btn_load_signin.setBorderPainted(false);
        btn_load_signin.setFocusPainted(false);
        btn_load_signin.setFocusable(false);
        btn_load_signin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_load_signin.setIconTextGap(25);
        btn_load_signin.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btn_load_signin.setPreferredSize(new java.awt.Dimension(50, 20));
        btn_load_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load_signinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_load_income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_expenses, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(btn_load_goals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load_signin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_profile_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_load_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(808, 808, 808))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addComponent(pnl_profile_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_load_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_income, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_load_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(btn_load_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        btn_close.setBackground(new java.awt.Color(204, 0, 0));
        btn_close.setFont(new java.awt.Font("Diodrum Cyrillic Semibold", 0, 14)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("X");
        btn_close.setActionCommand("");
        btn_close.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_close.setBorderPainted(false);
        btn_close.setDefaultCapable(false);
        btn_close.setFocusPainted(false);
        btn_close.setFocusable(false);
        btn_close.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_control_barLayout = new javax.swing.GroupLayout(pnl_control_bar);
        pnl_control_bar.setLayout(pnl_control_barLayout);
        pnl_control_barLayout.setHorizontalGroup(
            pnl_control_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_control_barLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_control_barLayout.setVerticalGroup(
            pnl_control_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pane_load_ui.setMaximumSize(new java.awt.Dimension(788, 600));
        pane_load_ui.setPreferredSize(new java.awt.Dimension(788, 600));
        pane_load_ui.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_design1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_control_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_load_ui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_design1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_control_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pane_load_ui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_load_incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_incomeActionPerformed
        VIncomeManagement pnl = new VIncomeManagement();
        SwitchUI(pnl);
        SetButtonColor(btn_load_income);
    }//GEN-LAST:event_btn_load_incomeActionPerformed

    private void btn_load_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_expensesActionPerformed
        VExpenseManagement pnl = new VExpenseManagement();
        SwitchUI(pnl);
        SetButtonColor(btn_load_expenses);
    }//GEN-LAST:event_btn_load_expensesActionPerformed

    private void btn_load_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_dashboardActionPerformed
        VDashboard pnl = new VDashboard();
        SwitchUI(pnl);
        SetButtonColor(btn_load_dashboard);
    }//GEN-LAST:event_btn_load_dashboardActionPerformed

    private void btn_load_goalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_goalsActionPerformed
        
        VGoalManagement pnl = new VGoalManagement();
        SwitchUI(pnl);
        SetButtonColor(btn_load_goals);
    }//GEN-LAST:event_btn_load_goalsActionPerformed

    private void btn_load_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_reportsActionPerformed
        VReportFrom pnl = new VReportFrom();
        SwitchUI(pnl);
        SetButtonColor(btn_load_reports);
    }//GEN-LAST:event_btn_load_reportsActionPerformed

    private void btn_load_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load_signinActionPerformed
        VSignIn vsi = new VSignIn();
        vsi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_load_signinActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new VHome().setVisible(true);            
            }            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_load_dashboard;
    private javax.swing.JButton btn_load_expenses;
    private javax.swing.JButton btn_load_goals;
    private javax.swing.JButton btn_load_income;
    private javax.swing.JButton btn_load_reports;
    private javax.swing.JButton btn_load_signin;
    private javax.swing.JLabel lbl_accemail;
    private javax.swing.JLabel lbl_pfp;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLayeredPane pane_load_ui;
    private javax.swing.JPanel pnl_control_bar;
    private javax.swing.JPanel pnl_design1;
    private keeptoo.KGradientPanel pnl_menu;
    private javax.swing.JPanel pnl_profile_info;
    // End of variables declaration//GEN-END:variables
}
